id = "admin-persona"
name = "Admin User"
description = "System administrator"
goal = "Manage system"

[metadata]
created_at = "2025-11-14T03:18:04.946660150Z"
updated_at = "2025-11-14T03:18:04.946660150Z"
